### ISSUE TITLE
yarn build fails

### ISSUE THREAD

**Issue by tevdoradze** [solana-labs/wallet-adapter#152]
**Describe the bug**
yarn build yields the following error:
```
lerna ERR! yarn run build stderr:
Failed to compile.

./pages/_app.tsx:1:37
Type error: Cannot find module '@solana/wallet-adapter-react-ui' or its corresponding type declarations.

> 1 | import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
```

**To Reproduce**
1. git clone
2. yarn install
3. yarn build

**Desktop (please complete the following information):**
 - OS: ubuntu 21.04
 - Browser chrome
 - Version 92.0.4515.159

**Comment by jordansexton** [comment]
Thanks for the report, this was introduced by https://github.com/solana-labs/wallet-adapter/pull/146. Fixing now.

**Comment by jordansexton** [comment]
Fixed by 83345e998e2b93d72870241ee0e659205f4bb2bc
